--------------------------------------------
-- HOTEL_INFO CREATE
--------------------------------------------

CREATE TABLE HOTEL_INFO
   (	ID NUMBER, 
	NAME VARCHAR2(124 BYTE), 
	ADDRESS VARCHAR2(124 BYTE), 
	TYPE VARCHAR2(20 BYTE), 
	TEL VARCHAR2(20 BYTE), 
	EMAIL VARCHAR2(124 BYTE), 
	RATING NUMBER, 
	X VARCHAR2(32 BYTE), 
	Y VARCHAR2(32 BYTE)
   );
   
ALTER TABLE HOTEL_INFO MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE HOTEL_INFO ADD CONSTRAINT "HOTEL_INFO_PK" PRIMARY KEY ("ID");