--------------------------------------------
-- ROOMS CREATE
--------------------------------------------
 CREATE TABLE ROOMS
   (	RO_NUM NUMBER, 
	HOTEL_ID NUMBER, 
	RO_TYPE VARCHAR2(20 BYTE), 
	RO_PRICE NUMBER, 
	RO_COUNT NUMBER, 
	CHECKIN NUMBER, 
	CHECKOUT NUMBER
   );
   
    CREATE UNIQUE INDEX ROOMS_PK ON ROOMS (RO_NUM);
    
     ALTER TABLE ROOMS MODIFY (RO_NUM NOT NULL ENABLE);
  ALTER TABLE ROOMS ADD CONSTRAINT ROOMS_PK PRIMARY KEY (RO_NUM);